version: 0.2

phases:
  pre_build:
    commands:
      - echo Install dependencies
      - npm install
      - echo Update build date
      - ./node_modules/.bin/apv update build
      - echo Copy appversion.json to public
      - cp appversion.json ./public/appversion.json
  build:
    commands:
      - echo Build app on `date`
      - npm run build
  post_build:
    commands:
      - echo Copy files to root
      - aws s3 sync ./build s3://wow.gnarlybits.com
      - echo Build completed on `date`

artifacts:
  base-directory: build
  files:
    - '**/*'
