version: 0.2

phases:
  pre-build:
    commands:
      - echo Install dependencies
      - npm install
  build:
    commands:
      - echo Build app on `date`
      - npm run build
  post-build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: build
  files:
    - '**/*'
